name: Root-Me JSON Stats
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  root-me-stats:
    name: Get Root-Me Personal Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: fjogeleit/http-request-action@master
        id: root-me-result
        with:
          url: 'https://api.www.root-me.org/auteurs/96411'
          method: 'GET'
          customHeaders: '{"Cookie": "api_key=${{ secrets.ROOT_ME_API_KEY }}"}'
      - name: Create JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "root-me-stats.json"
          json: ${{ steps.root-me-result.outputs.response }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated Root-Me stats
          skip_dirty_check: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}